### PR TITLE
Add invaders laser and spaceship lives

### PR DESCRIPTION
**Pull request by vinTibo**
There is a lot of room for improvement.

### CODE REVIEW

**Comment by lpnh** [comment]
well, well, well.. look who decided to show up, pretending they haven’t forgotten everything. yea, you guessed it — it’s-a me

i made some changes to your implementation, but i still want to give it some love before merging

it feels good to be back

**Comment by lpnh** [comment]
i think this is it. could you please take a look?

**Comment by vinTibo** [comment]
We should use a condition that prevents an invader from firing if there is a living invader below it in the same column.

**Comment by vinTibo** [comment]
Well done!

**Pull request merged**
